version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8890:9000"  # Web UI
      - "8001:8000"  # เปลี่ยนพอร์ตจาก 8000 เป็น 8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - portainer_network

volumes:
  portainer_data:
    driver: local

networks:
  portainer_network:
    driver: bridge