version: '3.8'

services:
  nginxproxy:
    container_name: nginxproxy
    image: 'jc21/nginx-proxy-manager:latest'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    ports:
      - '80:80'   # เปลี่ยนพอร์ต 80 เป็น 8080
      - '81:81'   # เปลี่ยนพอร์ต 81 เป็น 8081
      - '443:443'  # เปลี่ยนพอร์ต 443 เป็น 8443
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
